Add testing module cr-usecases
thefuntasty/mvvm-android pull request #104
Opened 2020-01-07 08:16 UTC by SumeraMartin

2020-01-27 14:01 UTC, davidkocnar requested changes
All tests in the `cr-usecases-test` module work smoothly. A problem is in the test written in the `example` module.

2020-01-27 14:01 UTC, davidkocnar commented on example/src/test/java/com/thefuntasty/mvvmsample/ui/form/FormViewModelTest.kt
> +        mockSaveFormUseCase.everyExecute(inputArgs) { "A" to "B" }
`everyExecute` function is not found here (whole file), maybe it was meant to be `mockExecute` instead.

2020-01-29 09:44 UTC, SumeraMartin commented on example/src/test/java/com/thefuntasty/mvvmsample/ui/form/FormViewModelTest.kt
> +        mockSaveFormUseCase.everyExecute(inputArgs) { "A" to "B" }
Fixed

2020-01-29 09:48 UTC, davidkocnar approved these changes

2020-01-29 09:49 UTC, merged