Feature/migrate arkitekt
thefuntasty/mvvm-android pull request #125
Opened 2020-04-08 09:25 UTC by okalman

2020-04-09 09:51 UTC, matejcikm requested changes

2020-04-09 09:51 UTC, matejcikm commented on cr-interactors/build/generated/source/buildConfig/debug/com/thefuntasty/mvvm/crinteractors/BuildConfig.java
> +public final class BuildConfig {
This is generated file.

2020-04-09 09:51 UTC, matejcikm commented on interactors/build/generated/source/buildConfig/debug/com/thefuntasty/mvvm/interactors/BuildConfig.java
> +public final class BuildConfig {
Why is this here? 🤔

2020-04-14 11:33 UTC, skywall approved these changes

2020-04-14 11:50 UTC, matejcikm approved these changes

2020-04-14 12:37 UTC, merged