Added common binding adapters
thefuntasty/mvvm-android pull request #28
Opened 2019-03-14 13:53 UTC by okalman

2019-03-14 14:02 UTC, matejcikm requested changes

2019-03-14 14:02 UTC, matejcikm commented on bindingadapters/src/main/java/com/example/bindingadapters/ViewExtensions.kt
> +fun View.visible() {
Tieto extensions nie su binding adapter, nedaval by som ich sem

2019-03-18 14:50 UTC, voneskuba approved these changes

2019-03-21 15:55 UTC, skywall commented
@matejcikm okej?

2019-03-21 15:56 UTC, skywall approved these changes

2019-03-21 16:01 UTC, matejcikm approved these changes

2019-03-21 16:49 UTC, merged